### ISSUE TITLE
Steam integration

### ISSUE THREAD

**Issue by nicatronTg** [NyxStudios/ModBox#8]
![Steamworks](http://i.imgur.com/y0xvntI.png)

This is the global issue for Steam master server integration.

One of the biggest problems Terraria has is that it is difficult for users to be authenticated and tied to Steam accounts. This is not a new problem -- White Lotus attempts to solve this by adding additional stages to the TShock registration process, but this can be simplified by controlling the server and the client.

There are three main solutions that we can implement in ModBox that will allow for Steam integration, i.e. verification of Steam tickets similar to how Source games work.

# Steam depot #

If Terraria got a Steam depot for the server, or if we got the ability to release a standalone mod, we have our own Steam depot. This means that we can simply add the Steamworks SDK to the server and the client and perform the handshake as per Valve's official documentation. Easy, but requires Re-Logic to move, and I've already pushed this a bit. Not sure what will happen.

# Replace Terraria #

The next solution requires server owners to own a copy of Terraria for their server. This copy of Terraria has to be on Windows, which makes Mono Steam integration impossible. They must replace the Terraria executable installed for that Steam account with the ModBox server, and start the server through Steam. This means that the server has to be extremely robust in not crashing, which is a key point. The server must also be on a computer with a reliable connection to the Steam network -- disconnection will render its auth ticket invalid. The downsides here are enormous:

* Steam clients are more unreliable than servers. Can disconnect from Steam intermittently, crash, or become dissociated and require manual intervention to fix.
* Costs $9.99 per server to run.
* Cannot run multiple servers concurrently on the same machine without installing multiple Steam clients on the same machine.
* Requires Windows servers with UI access.

# Roll our own master server #

In this scenario, we run our own master server, replacing Terraria in our server with an executable we run, which validates Steam tickets for all ModBox users. While Steam may still be unreliable in this situation, connected to a dedicated server with reliable infrastructure can mitigate the problem. By storing Steam tickets, we can also reboot our master server if it becomes dissociated with Steam and reclaim tickets if necessary. Server owners don't need to worry about any requirements, it "just works."

# Conclusion #

Right now, we're going to experiment with going with my final solution to implement Steam. While this requires more cost overhead, we can probably recoup the cost in some other form, by charging server owners to use additional features of our master server in addition to Steam auth.

# Todo List #

This todo list is ordered in order of what I'm working on, first to last.

- [ ] Build server for connecting, relaying, and distributing Steam auth information to clients and servers.
- [ ] Integrate with server as a late check (post join).
- [ ] Integrate with client as a late check (post join).
- [ ] Integrate with server as an early check (during initial server + client handshake).
- [ ] Integrate with client as an early check (either during initial startup of the game client or during the handshake with the server).
- [ ] Deploy test server on some infrastructure for prototype testing.
